Support 1.23 iterator for set
deckarep/golang-set pull request #140
Opened 2024-08-02 04:11 UTC by amikai

This PR use to discussion.

2025-02-28 20:02 UTC, freeformz commented
FWIW: I'd really like to see this.
If this is stalled I'm happy to open a new PR.

2025-03-03 15:18 UTC, amikai commented
Hi @freeformz, @deckarep. The PR is currently in draft because it’s still under discussion in #141. Once the discussion is finalized and a decision is reached, feel free to ping me to continue developing this PR.

2025-03-03 16:18 UTC, deckarep commented
@amikai and @freeformz - it looks like you both want your PR’s merged on Iterator support for this package.

I appreciate both of your efforts on this but both PR’s are quite different. freeformz looks to be a significant change at the moment while amikai’s is much smaller in scope and looks to be much more straightforward.

Let me be be clear: I want to support iterators but when this was initially proposed it felt too early to just jump in  without a better understanding of the best way forward. This is why I didn’t rush to merge it. It’s also why I don’t rush to merges everyone’s changes.

Some significant projects are using this package and any abrupt changes which cause confusion, frustration will cause these projects to quickly fork and/or abandon this repo.

So as it stands I’m interested in taking the least breaking changes, with the least scope currently. Additionally, I want to ensure that methods are deprecated overtime and not overnight.

So with all of that said, @amikai - it seems like the last thing we had to come to agreement on was just the naming of the iterator method? And it looks like `Values ` should work just fine?

@freeformz - your input is still welcome but I want to introduce smaller scopes changes at this time. As more people migrate to later versions of Go I will consider cutting a V3 release.

2025-03-03 20:44 UTC, deckarep requested changes

2025-03-03 20:44 UTC, deckarep commented on .github/workflows/ci.yml
> +        go-version: [1.20.x, 1.21.x, 1.22.x, 1.23.0-rc.2]
Maybe time to update these to reflect the state of the current versions.

2025-03-03 20:44 UTC, deckarep commented on set.go
> +func Values[T comparable](s Set[T]) func(func(element T) bool) {
Since this is on the interface, would you mind adding the respective comments for the `Values` method?

2025-03-03 20:44 UTC, deckarep commented on set.go
> +func Values[T comparable](s Set[T]) func(func(element T) bool) {
I still prefer `Elements`, since Set's have elements. Let's make a final decision here and be done with it. As they say: naming things is hard but it's time to move forward on this PR. /cc @amikai

2025-03-03 23:11 UTC, amikai commented on .github/workflows/ci.yml
> +        go-version: [1.20.x, 1.21.x, 1.22.x, 1.23.0-rc.2]
update in aab5b006e856a51306d607c70fa473b073040b66

2025-03-03 23:13 UTC, amikai commented on set.go
> +func Values[T comparable](s Set[T]) func(func(element T) bool) {
Comment is added in 24f21dd8caecdd4ecea9a21e6fa5a437ef369841

2025-03-04 00:24 UTC, deckarep approved these changes
LGTM

2025-03-04 00:25 UTC, merged